baseURL = 'https://yuhuanowo.github.io'
languageCode = 'zh-tw'
title = 'Yuhuan-blog'
buildFuture = false
theme = "PaperMod"

[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10


[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "Yuhuan"
subtitle = "Yuhuan's Blog"
imageUrl = "https://www.yuhuanstudio.tech/assets/img/342x290xIMG_0136.jpg.pagespeed.ic.e8PKRQ6DJn.webp"
imageWidth = 120
imageHeight = 120
imageTitle = "Enter the content"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"


[[params.socialIcons]]
name = "github"
url = "https://github.com/yuhuanowo"
#...more

[[params.socialIcons]]
name = "website"
url = "https://www.yuhuanstudio.tech"


[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視